spring:
  application:
    name: gavin-admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:8989
server:
  port: 8990



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS